clusterName: k8s
isSupportRouteDomain: true
##AS3 basic configuration
##Multi-cluster docking single BIG-IP, controller Common init and remote log
masterCluster: k8s
schemaVersion: "3.29.0"
iRule:
  - bwc-1mbps-irule
  - bwc-2mbps-irule
  - bwc-3mbps-irule
tenant:
  ##common partiton config, init AS3 needs
  - name: "Common"
    namespaces: "dwb-test1,dwb-test"
    virtualService:
      template: ''
      virtualAddresses:
        virtualAddress: "0.0.0.0"
        icmpEcho: "disable"
        arpEnabled: false
        template: ''
    gwPool:
      serverAddresses:
        - "192.168.10.1"
  - name: p2
    namespaces: default
    routeDomain:
      id: 2
      name: "rd2"
    virtualService:
      template: ""
      virtualAddresses:
        virtualAddress: "0.0.0.0"
        icmpEcho: "disable"
        arpEnabled: false
        template: ''
    gwPool:
      serverAddresses:
        - "1.16.10.22"
        - "192.168.10.22"
  - name: project3
    namespaces: project3,test-ns-a
    routeDomain:
      id: 4
      name: "rd4"
    virtualService:
      template: '{
                 "layer4": "any",
                 "translateServerAddress": false,
                 "translateServerPort": false,
                 "virtualAddresses": [
                     "1.1.0.0"
                 ],
                 "policyFirewallEnforced": {
                     "use": "/{{tenant}}/Shared/k8s_svc_policy_rd3"
                 },
                 "securityLogProfiles": [
                     {
                         "use": "/{{tenant}}/Shared/k8s_afm_hsl_log_profile"
                     }
                 ],
                 "virtualPort": 0,
                 "snat": "auto",
                 "class": "Service_L4",
                 "pool": "k8s_gw_pool"
             }'
      virtualAddresses:
        virtualAddress: "0.0.0.0"
        icmpEcho: "disable"
        arpEnabled: false
        template: ''
    gwPool:
      serverAddresses:
        - "10.16.10.23"
logPool:
  loggingEnabled: false
  enableRemoteLog: false
  serverAddresses:
    - "1.2.3.4"
  template: '{
                 "k8s_afm_hsl_log_profile": {
                     "network": {
                         "publisher": {
                             "use": "/{{tenant}}/Shared/k8s_firewall_hsl_log_publisher"
                         },
                         "storageFormat": {
                             "fields": [
                                 "bigip-hostname",
                                 "acl-rule-name",
                                 "acl-policy-name",
                                 "acl-policy-type",
                                 "protocol",
                                 "action",
                                 "drop-reason",
                                 "context-name",
                                 "context-type",
                                 "date-time",
                                 "src-ip",
                                 "src-port",
                                 "vlan",
                                 "route-domain",
                                 "dest-ip",
                                 "dest-port"
                             ]
                         },
                         "logRuleMatchAccepts": true,
                         "logRuleMatchRejects": true,
                         "logRuleMatchDrops": true,
                         "logIpErrors": true,
                         "logTcpErrors": true,
                         "logTcpEvents": true
                     },
                     "class": "Security_Log_Profile"
                 },
                 "k8s_firewall_hsl_log_publisher": {
                     "destinations": [
                         {
                             "use": "/{{tenant}}/Shared/k8s_remote-hsl-dest"
                         },
                         {
                             "use": "/{{tenant}}/Shared/k8s_remote-hsl-dest-format"
                         },
                         {
                             "bigip": "/{{tenant}}/local-db"
                         }
                     ],
                     "class": "Log_Publisher"
                 },
                 "k8s_remote-hsl-dest": {
                     "pool": {
                         "use": "/{{tenant}}/Shared/k8s_log_pool"
                     },
                     "class": "Log_Destination",
                     "type": "remote-high-speed-log"
                 },
                 "k8s_remote-hsl-dest-format": {
                     "format": "rfc5424",
                     "remoteHighSpeedLog": {
                         "use": "/{{tenant}}/Shared/k8s_remote-hsl-dest"
                     },
                     "class": "Log_Destination",
                     "type": "remote-syslog"
                 }
             }'



